# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Python tests

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/check
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run Integration Tests
        id: int_test
        if: success() || failure()
        run: |
          uv run -m unittest discover ./tests/ -v -p "test_int*"
      - name: Run unit tests with coverage
        id: unit_test
        if: success() || failure()
        run: |
          uv run -m coverage run -m unittest discover ./tests/ -v -p "test_unit*"
      - name: Measure coverage
        if: success() || failure()
        run: |
          uv run -m coverage report -m --fail-under=100
